/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MyChecksRouteImport } from './routes/my-checks'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as CompleteIdRouteImport } from './routes/complete.$id'
import { Route as InspectionNewRouteImport } from './routes/inspection.new'
import { Route as ResultsIdRouteImport } from './routes/results.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MyChecksRoute = MyChecksRouteImport.update({
  id: '/my-checks',
  path: '/my-checks',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteIdRoute = CompleteIdRouteImport.update({
  id: '/complete/$id',
  path: '/complete/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionNewRoute = InspectionNewRouteImport.update({
  id: '/inspection/new',
  path: '/inspection/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/my-checks': typeof MyChecksRoute
  '/reference': typeof ReferenceRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/supervisor': typeof SupervisorRoute
  '/complete/$id': typeof CompleteIdRoute
  '/inspection/new': typeof InspectionNewRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/my-checks': typeof MyChecksRoute
  '/reference': typeof ReferenceRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/supervisor': typeof SupervisorRoute
  '/complete/$id': typeof CompleteIdRoute
  '/inspection/new': typeof InspectionNewRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/my-checks': typeof MyChecksRoute
  '/reference': typeof ReferenceRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/supervisor': typeof SupervisorRoute
  '/complete/$id': typeof CompleteIdRoute
  '/inspection/new': typeof InspectionNewRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/my-checks'
    | '/reference'
    | '/reports'
    | '/settings'
    | '/supervisor'
    | '/complete/$id'
    | '/inspection/new'
    | '/results/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/my-checks'
    | '/reference'
    | '/reports'
    | '/settings'
    | '/supervisor'
    | '/complete/$id'
    | '/inspection/new'
    | '/results/$id'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/my-checks'
    | '/reference'
    | '/reports'
    | '/settings'
    | '/supervisor'
    | '/complete/$id'
    | '/inspection/new'
    | '/results/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  MyChecksRoute: typeof MyChecksRoute
  ReferenceRoute: typeof ReferenceRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SupervisorRoute: typeof SupervisorRoute
  CompleteIdRoute: typeof CompleteIdRoute
  InspectionNewRoute: typeof InspectionNewRoute
  ResultsIdRoute: typeof ResultsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-checks': {
      id: '/my-checks'
      path: '/my-checks'
      fullPath: '/my-checks'
      preLoaderRoute: typeof MyChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete/$id': {
      id: '/complete/$id'
      path: '/complete/$id'
      fullPath: '/complete/$id'
      preLoaderRoute: typeof CompleteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection/new': {
      id: '/inspection/new'
      path: '/inspection/new'
      fullPath: '/inspection/new'
      preLoaderRoute: typeof InspectionNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$id': {
      id: '/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  MyChecksRoute: MyChecksRoute,
  ReferenceRoute: ReferenceRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SupervisorRoute: SupervisorRoute,
  CompleteIdRoute: CompleteIdRoute,
  InspectionNewRoute: InspectionNewRoute,
  ResultsIdRoute: ResultsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
